spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.graduation.design.hotel.model